SELECT DISTINCT ?code WHERE {
	?model a <Model>;
		rdfs:label ?model_lbl .
	FILTER(STR(?model_lbl) = 'Depth DDPPO')
	?benchmark <has_dataset> ?dataset .
	?cont <has_benchmark> ?benchmark .
	?cont <has_model> ?model;
		<has_source code> ?code .
}
