SELECT DISTINCT ?code WHERE {
	?model a orkgc:Model;
		rdfs:label ?model_lbl .
	FILTER(STR(?model_lbl) = 'Depth DDPPO')
	?benchmark orkgp:HAS_DATASET ?dataset .
	?cont orkgp:HAS_BENCHMARK ?benchmark .
	?cont orkgp:HAS_MODEL ?model;
		orkgp:HAS_SOURCE_CODE ?code .
}

SELECT ?paperTitle ?codeLink WHERE {
	 ?paper orkgp:HAS_MODEL orkg:R123481 .
	 ?paper rdfs:label ?paperTitle .
	 ?paper orkgp:HAS_SOURCE_CODE ?codeLink .
}
